### ISSUE TITLE
域名解析过不了

### ISSUE THREAD

**Issue by bactdt** [daycat/proxypool#5]
域名解析地址一直过不了，我查看过地址都是对的，指向也是对的!![image](https://user-images.githubusercontent.com/81372089/155743983-54335030-b603-4dfe-add3-eda1da2c9de1.jpeg)![image](https://user-images.githubusercontent.com/81372089/155743992-162f03c1-d426-4485-9650-881038c6bbf8.jpeg)![image](https://user-images.githubusercontent.com/81372089/155744001-c5d8fc2f-ea79-485c-b57f-47ad3a41dbf1.jpeg)

**Comment by daycat** [comment]
已修复
